"""create users table

Revision ID: 2eaac5a76f91
Revises:
Create Date: 2025-08-20 15:33:34.180396

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "2eaac5a76f91"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
