"""Added Table StateTypes and RegisterBrand

Revision ID: 3ba73a88234b
Revises: 9b17708800f6
Create Date: 2025-08-20 16:57:19.999808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba73a88234b'
down_revision: Union[str, Sequence[str], None] = '9b17708800f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_state_type_id'), 'state_type', ['id'], unique=False)
    op.create_table('register_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_title', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_type_id'], ['state_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_brand_id'), 'register_brand', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_brand_id'), table_name='register_brand')
    op.drop_table('register_brand')
    op.drop_index(op.f('ix_state_type_id'), table_name='state_type')
    op.drop_table('state_type')
    # ### end Alembic commands ###
