"""Refactorice table refresh token

Revision ID: 9b17708800f6
Revises: fa7f02ac0bc9
Create Date: 2025-08-20 16:26:06.235321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b17708800f6'
down_revision: Union[str, Sequence[str], None] = 'fa7f02ac0bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.Text(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('access_token', sa.Text(), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'is_revoked')
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.drop_column('refresh_tokens', 'access_token')
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###
