"""Added table of roletype

Revision ID: cb8daf733b97
Revises: 3ba73a88234b
Create Date: 2025-08-21 09:51:15.888535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8daf733b97'
down_revision: Union[str, Sequence[str], None] = '3ba73a88234b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_role_type_id'), 'role_type', ['id'], unique=False)
    op.add_column('users', sa.Column('role_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'role_type', ['role_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_type_id')
    op.drop_index(op.f('ix_role_type_id'), table_name='role_type')
    op.drop_table('role_type')
    # ### end Alembic commands ###
